backend:
  name: git-gateway
  branch: main

media_folder: "images"

media_library:
  name: uploadcare
  config:
    publicKey: 3debd9c2baceaef3585d
    multiple: true
  settings:
    defaultOperations: '/resize/2400/-/quality/lightest/-/format/auto/'

collections:
  - name: "work"
    label: "Work" 
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "string", default: "work" }
      - { label: "Categories", name: "categories", widget: "string" }
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Medium", name: "materials", widget: "string", required: false}
      - { label: "Dimensions", name: "dimensions", widget: "string", required: false }
      - { label: "Images", name: "images", widget: "image" }
  - name: "about"
    label: "About" 
    folder: "_posts/about"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "string", default: "post" }
      - { label: "Categories", name: "categories", widget: "string", default: "about" }
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Images", name: "images", widget: "image", required: false}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pet_portrait_text"
    label: "Pet Portrait Text" 
    folder: "_posts/pet_portrait_text"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "string", default: "post" }
      - { label: "Categories", name: "categories", widget: "string", default: "pet_portrait_text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "landing_page"
    label: "Landing Page" 
    folder: "_posts/landing_page"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "string", default: "post" }
      - { label: "Categories", name: "categories", widget: "string", default: "landing_page" }
      - { label: "Images", name: "images", widget: "image", required: true}
  - name: "cv"
    label: "CV" 
    folder: "_posts/cv"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "string", default: "post" }
      - { label: "Categories", name: "categories", widget: "string", default: "cv" }
      - { label: "Body", name: "body", widget: "markdown" }
